name: ci
on:
  pull_request:
    branches: [main]
env:
  Name: 'Job'
jobs:
  lint:
    runs-on: ubunto@latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Node
      uses: actions/setup-node@v7
    - name: Install dependency
      run: npm ci
    - run: echo {env.Name}


